### ISSUE TITLE
Enabling Security for the Kafka

### ISSUE THREAD

**Issue by yhilem** [wso2-extensions/siddhi-io-kafka#26]
Hi,
It would be useful, like the ESB connectors (https://docs.wso2.com/display/ESBCONNECTORS/Enabling+Security+for+the+Kafka+Connector+and+Inbound+Endpoint), to add security for kafka source & sink.

Thanks
Youcef HILEM

**Comment by ramindu90** [comment]
Hi @yhilem ,

You can configure kafka source and sinks as below.


@source( 
type="kafka", 
topic.list="kafka_topic",
        partition.no.list="0",
        threading.option="single.thread",
        group.id="group",
        bootstrap.servers="localhost:9093",
        **optional.configuration**="
&nbsp;&nbsp;&nbsp;security.protocol:SASL_SSL, 
&nbsp;&nbsp;&nbsp;sasl.kerberos.service.name:kafka, 
&nbsp;&nbsp;&nbsp;sasl.jaas.config:/Users/ramindu/Desktop/kafka_sec/jaas.conf',
&nbsp;&nbsp;&nbsp;ssl.truststore.location:'/Users/ramindu/Desktop/kafka_sec/kafka.server.truststore.jks',
&nbsp;&nbsp;&nbsp;ssl.truststore.password:wso2carbon,
&nbsp;&nbsp;&nbsp;ssl.keystore.location:'/Users/ramindu/Desktop/kafka_sec/kafka.server.keystore.jks',
&nbsp;&nbsp;&nbsp;ssl.keystore.password:wso2carbon,ssl.key.password:wso2carbon",
@map(type="json"))
define stream SweetProductionStream (name string, amount double);


The user has the ability to add the optional parameters (optional.configuration) as above and give the values as key value pairs separated with commas. 
eg: security.protocol:SASL_SSL, sasl.kerberos.service.name:kafka

Best Regards,
Ramindu.

**Comment by niveathika** [comment]
Closing the issue, as it was answered.
