### ISSUE TITLE
Cannot process messages from Kafka 0.11.0.1

### ISSUE THREAD

**Issue by mikestov** [wso2-extensions/siddhi-io-kafka#41]
**Description:**

I am working on integrating Siddhi with Kafka by using the io-kafka extension and json. I'm running Kafka 0.11.0.1 locally. Things were working OK when I was sending invalid json messages into Kafka -- Siddhi was outputting a format error which I was expecting. When I sent a json message which was correct, Siddhi would lock up and my Kafka queue would need to be flushed to work again. Just to make sure it wasn't Kafka, I used spring-kafka to process messages on the same queue with no problem (using kafka-client jar 0.11.0.1) and I was able to feed events into Siddhi using the InputHandler and it was working great.

I noticed siddhi-io-kafka is currently using a much older kafka-client jar (0.9.x), which may be causing the issue. I tried forcing my dependencies to include the latest kafka-client instead of 0.9.x, however there is a binary incompatibility between the versions and Siddhi would need to have a method signature changed to work with the newer kafka client. 

**Affected Product Version:**

Latest siddhi-io-kafka release

**OS, DB, other environment details and versions:**    

Mac OS X, Kafka 0.11.0.1

**Comment by sahandilshan** [comment]
I have tested this issue with the latest siddhi-io-kafka (Siddhi IO Kafka 5.0.5) version and the Kafka 0.11.0.1 broker and this issue does not occur anymore.

**Comment by mohanvive** [comment]
Closing the issue as per above comment..
