### ISSUE TITLE
Kafka Source with Kerberos SASL

### ISSUE THREAD

**Issue by flolas** [wso2-extensions/siddhi-io-kafka#79]
**Description:**
Hi.
I want to know if this extension support Kerberos+SASL. Thank!

**Suggested Labels:**
Type/Question

**Comment by ramindu90** [comment]
Hi @flolas ,

Optional configurations other than the mandatory configurations can be added to the Kafka source and sink using the **optional.configuration** parameter.
The values can be given as key value pairs separated with commas. eg: security.protocol:SASL_SSL, sasl.kerberos.service.name:kafka 
We create the kafka consumer and producer using mandatory + optional configs.

eg: 

@source( 
type="kafka", 
topic.list="kafka_topic",
        partition.no.list="0",
        threading.option="single.thread",
        group.id="group",
        bootstrap.servers="localhost:9093",
        **optional.configuration**="
&nbsp;&nbsp;&nbsp;security.protocol:SASL_SSL, 
&nbsp;&nbsp;&nbsp;sasl.kerberos.service.name:kafka, 
&nbsp;&nbsp;&nbsp;sasl.jaas.config:/Users/ramindu/Desktop/kafka_sec/jaas.conf',
&nbsp;&nbsp;&nbsp;ssl.truststore.location:'/Users/ramindu/Desktop/kafka_sec/kafka.server.truststore.jks',
&nbsp;&nbsp;&nbsp;ssl.truststore.password:wso2carbon,
&nbsp;&nbsp;&nbsp;ssl.keystore.location:'/Users/ramindu/Desktop/kafka_sec/kafka.server.keystore.jks',
&nbsp;&nbsp;&nbsp;ssl.keystore.password:wso2carbon,ssl.key.password:wso2carbon",
@map(type="json"))
define stream SweetProductionStream (name string, amount double);

Best Regards,
Ramindu.

**Comment by niveathika** [comment]
Closing the issue, as it was answered.
