### ISSUE TITLE
Avro support

### ISSUE THREAD

**Issue by MacNale** [wso2-extensions/siddhi-io-kafka#84]
**Description:**
Support Avro

**Suggested Labels:**
avro,kafka,source,sink

**Comment by niveathika** [comment]
Hi @MacNale,

Avro map support feature is currently ongoing development. This will be released ASAP.

Please see [siddhi-map-avaro](https://github.com/wso2-extensions/siddhi-map-avro) repository for reference.

**Comment by niveathika** [comment]
Closing this as this support is released as of today.

**Comment by MacNale** [comment]
Thank you!!
